---
title: "Kriging_Transformations"
author: "Cher Petersen"
date: "2023-11-08"
output:
  word_document: default
  html_document: default
---
git clone <repository_url>

```{r}
library(geoR)
points(sic.100, borders=sic.borders,col="green")###sample
points(sic.367, borders=sic.borders,col="purple",add=TRUE)###control
```

```{r}
plot.geodata(sic.100,bor=sic.borders)
```

```{r}
library(fields)
vario.b<- variog(sic.100,option =c ("bin", "cloud", "smooth"),
bin.cloud=TRUE)
plot(vario.b)
```


```{r}
vario.c <- variog(sic.100, op="cloud")
bplot.xy(vario.c$u,vario.c$v, breaks=vario.b$u,col="grey80",
lwd=2,cex=0.1,outline=FALSE)
plot(vario.c)
```



```{r}
vario.ex<- variog(sic.100,option="bin")
vario.sphe<-(variofit(vario.ex,cov.model= "spher",
ini.cov.pars=c(15000,200)))
par(mfrow=c(2,2), mar=c(3,3,1,1), mgp =c (2,1,0))
plot(vario.ex,main="Spherical")
lines.variomodel(cov.model="sphe",cov.pars=c(15000,100),
nug=0,max.dist=350)
plot(vario.ex,main="Exponential")
lines.variomodel(cov.model="exp",cov.pars=c(15000,100),
nug=0,max.dist=350)
```


```{r}
plot(vario.ex,main="Exponential with nugget effect")
lines.variomodel(cov.model="exp",cov.pars=c(10000,100),
nug=5000,max.dist=350)
plot(vario.ex,main="Exponential with nugget effect")
lines.variomodel(cov.model="matern",cov.pars=c(10000,100),
nug=0,max.dist=350,kappa=0.5)
```


```{r}
vario.ex<- variog(sic.100, bin.cloud=TRUE)
plot(vario.ex,main="")
lines.variomodel(cov.model="spher",cov.pars=c(15000,50),
nug=0,max.dist=300)
```



```{r}
pred.grid <- expand.grid(seq(0, 350, length.out = 51), seq(0, 220, length.out = 51))
rgb.palette <- colorRampPalette(c("blue", "lightblue", "orange", "red"), space = "rgb")
kc <- krige.conv(sic.100, loc = pred.grid,
                 krige = krige.control(cov.model = "spherical", cov.pars = c(15000, 50)))
image(kc, loc = pred.grid, col = rgb.palette(20), xlab = "Coord X",
      ylab = "Coord Y", borders = sic.borders, main = "Estimation")
krige.var <- kc$krige.var
image(kc, krige.var, loc = pred.grid, col = rgb.palette(20),
      xlab = "Coord X", ylab = "Coord Y", borders = sic.borders,
      main = "Kriging Variance")
```
```{r}
kc1<- krige.conv(sic.100, loc = sic.100$coords,
krige=krige.control(cov.model="spherical",cov.pars=c(16000,47)))
kc2<- krige.conv(sic.100, loc = sic.367$coords,
krige=krige.control(cov.model="spherical",cov.pars=c(16000,47)))

plot(sic.100$data,kc1$predict,xlab="Observed",ylab="Estimated",main="Control sample")
abline(a=0,b=1,col="red")

plot(sic.367$data,kc2$predict,xlab="Observed",ylab="Estimated",
main="Control")

abline(a=0,b=1,col="red")
```
```{r}
# Assuming you have a validation dataset in 'validation_data' with columns 'observed' and 'location'
# Also assuming 'kc1' and 'kc2' are the kriging results from the previous code

# Extract observed values from validation dataset for sample and control
observed_sample <- sic.100$data
observed_control <- sic.367$data 

# Extract kriging predictions for sample and control
predicted_sample <- kc1$predict
predicted_control <- kc2$predict
# Calculate RMSE for sample and control
rmse_sample <- sqrt(mean((observed_sample - predicted_sample)^2))
rmse_control <- sqrt(mean((observed_control - predicted_control)^2))

# Calculate covariance for sample and control
#covariance_sample <- cov(observed_sample, predicted_sample)[1, 2]
#covariance_control <- cov(observed_control, predicted_control)[1, 2]


cat("RMSE for Sample Data:", rmse_sample, " ")


cat("RMSE for Control Sample Data:", rmse_control, " ")

```


```{r}
library("geoR")
plot.geodata(sic.100,bor=sic.borders,lambda=0.5)
```

```{r}
library("geoR")
vario.ext <- variog(sic.100, option = "bin", lambda = 0.5)
plot(vario.ext)
lines.variomodel(cov.m = "mat", cov.p = c(105, 36), nug = 6.9,
                 max.dist = 300, kappa = 3, lty = 1)#### Testing k=3
```


```{r}
library("geoR")
vario.ext <- variog(sic.100, option = "bin", lambda = 0.5)
plot(vario.ext)
lines.variomodel(cov.m = "mat", cov.p = c(105, 36), nug = 6.9,
                 max.dist = 300, kappa = 2, lty = 1)#### Testing k=2
```


```{r}
library("geoR")
vario.ext <- variog(sic.100, option = "bin", lambda = 0.5)
plot(vario.ext)
lines.variomodel(cov.m = "mat", cov.p = c(105, 36), nug = 6.9,
                 max.dist = 300, kappa = 1, lty = 1)#### Preferred where k=1 
```

```{r}
library(geoR)
kct<- krige.conv(sic.100, loc = pred.grid,
krige=krige.control(cov.model="matern",cov.pars=c(105, 36),
kappa=3,nugget=6.9,lambda=0.5))#### Kriging analysis where k=3
pred.grid <- expand.grid(seq(0,350, l=51),seq (0,220, l=51))
rgb.palette <- colorRampPalette(c("blue", "lightblue",
"orange", "red"),space = "rgb")
image(kct, loc = pred.grid,col =rgb.palette(20) , xlab="Coord X",
ylab="Coord Y",borders=sic.borders,main="Estimation") 
krige.var1<- kct$krige.var
image(kct, krige.var1,loc = pred.grid,col =rgb.palette(20) ,
xlab="Coord X",ylab="Coord Y",borders=sic.borders,
main="Kriging variance")
```


```{r}
library(geoR)
kct<- krige.conv(sic.100, loc = pred.grid,
krige=krige.control(cov.model="matern",cov.pars=c(105, 36),
kappa=2,nugget=6.9,lambda=0.5))#### Kriging analysis where k=2
pred.grid <- expand.grid(seq(0,350, l=51),seq (0,220, l=51))
rgb.palette <- colorRampPalette(c("blue", "lightblue",
"orange", "red"),space = "rgb")
image(kct, loc = pred.grid,col =rgb.palette(20) , xlab="Coord X",
ylab="Coord Y",borders=sic.borders,main="Estimation") 
krige.var1<- kct$krige.var
image(kct, krige.var1,loc = pred.grid,col =rgb.palette(20) ,
xlab="Coord X",ylab="Coord Y",borders=sic.borders,
main="Kriging variance")
```

`
```{r}
library(geoR)
kct<- krige.conv(sic.100, loc = pred.grid,
krige=krige.control(cov.model="matern",cov.pars=c(105, 36),
kappa=1,nugget=6.9,lambda=0.5))#### Kriging analysis where k=1 (Preferred)
pred.grid <- expand.grid(seq(0,350, l=51),seq (0,220, l=51))
rgb.palette <- colorRampPalette(c("blue", "lightblue",
"orange", "red"),space = "rgb")
image(kct, loc = pred.grid,col =rgb.palette(20) , xlab="Coord X",
ylab="Coord Y",borders=sic.borders,main="Estimation") 
krige.var1<- kct$krige.var
image(kct, krige.var1,loc = pred.grid,col =rgb.palette(20) ,
xlab="Coord X",ylab="Coord Y",borders=sic.borders,
main="Kriging variance")

```
```{r}
library(geoR)
kct1<- krige.conv(sic.100, loc = sic.100$coords,
krige=krige.control(cov.model="matern",cov.pars=c(16000,47),
kappa=1,nugget=6.9,lambda=0.5))
kct2<- krige.conv(sic.100, loc = sic.367$coords,
krige=krige.control(cov.model="matern",cov.pars=c(160,47),
kappa=1,nugget=6.9,lambda=0.5))
plot(sic.100$data,kct1$predict,xlab="Observed",ylab="Estimated",
main="Sample")
abline(a=0,b=1,col="red")
plot(sic.367$data,kct2$predict,xlab="Observed",ylab="Estimated",
main="Control sample")
abline(a=0,b=1,col="red")
```

```{r}
# Assuming you have a validation dataset in 'validation_data' with columns 'observed' and 'location'
# Also assuming 'kct1' and 'kct2' are the kriging results from the previous code

# Extract observed values from validation dataset for sample and control
observed_sample <- sic.100$data
observed_control <- sic.367$data  

# Extract kriging predictions for sample and control
predicted_sample <- kct1$predict
predicted_control <- kct2$predict

# Calculate RMSE for sample and control
rmse_sample <- sqrt(mean((observed_sample - predicted_sample)^2))
rmse_control <- sqrt(mean((observed_control - predicted_control)^2))

# Calculate covariance for sample and control
#covariance_sample <- cov(observed_sample, predicted_sample)[1, 2]
#covariance_control <- cov(observed_control, predicted_control)[1, 2]

# Print RMSE and covariance
cat("RMSE for Sample Data:", rmse_sample)
#cat("Covariance for Sample Data:", covariance_sample, "\n")

cat("RMSE for Control Sample Data:", rmse_control)
#cat("Covariance for Control Sample Data:", covariance_control, "\n")
```


